# Generated by Django 4.2.6 on 2023-10-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='photo',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='portfolio/technologies'),
        ),
    ]
