# Generated by Django 4.2.6 on 2023-11-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
