# Generated by Django 4.2.6 on 2023-11-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
