# Generated by Django 4.2.6 on 2023-11-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_issuing_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.issuing_organization'),
        ),
    ]
