# Generated by Django 4.2.6 on 2023-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_portfolio_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
