# Generated by Django 4.2.6 on 2023-11-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_portfolio_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='object_fit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
