# Generated by Django 4.2.7 on 2023-11-22 04:40

import apps.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_personal_cv_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/about'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/main'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.portfolio.models.Portfolio.get_upload_to),
        ),
    ]
